# Generated by Django 2.0.2 on 2018-03-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reply_post'),
        ('users', '0003_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
