# Generated by Django 2.0.2 on 2018-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reply_post'),
        ('users', '0004_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='replies',
            field=models.ManyToManyField(to='posts.Reply'),
        ),
    ]
