# Generated by Django 2.0.2 on 2018-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_career_consultant',
            field=models.BooleanField(default=False),
        ),
    ]
